name: 'Taskmaster'
description: 'Automated task planning and issue management from Product Requirements Documents (PRDs)'
author: 'Taskmaster Team'

inputs:
  complexity-threshold:
    description: 'Maximum complexity threshold for task breakdown'
    required: false
    default: '40'
  max-depth:
    description: 'Maximum depth for automatic task recursion'
    required: false
    default: '3'
  prd-path-glob:
    description: 'Path glob pattern for PRD files'
    required: false
    default: 'docs/**.prd.md'
  breakdown-max-depth:
    description: 'Maximum depth for breakdown recursion'
    required: false
    default: '2'
  taskmaster-args:
    description: 'Additional arguments to pass to Taskmaster CLI'
    required: false
    default: ''
  github-token:
    description: 'GitHub token for API access'
    required: true
  action-mode:
    description: 'Action mode: generate, breakdown, watcher, or full'
    required: false
    default: 'full'
  scan-mode:
    description: 'Scan mode for watcher: webhook (single issue) or full (all issues)'
    required: false
    default: 'webhook'

outputs:
  task-graph:
    description: 'Path to generated task graph JSON file'
    value: ${{ steps.generate.outputs.task-graph }}
  issues-created:
    description: 'Number of issues created or updated'
    value: ${{ steps.generate.outputs.issues-created }}
  sub-issues-created:
    description: 'Number of sub-issues created during breakdown'
    value: ${{ steps.breakdown.outputs.sub-issues-created }}
  parent-issue-updated:
    description: 'Whether parent issue was updated with sub-issue links'
    value: ${{ steps.breakdown.outputs.parent-issue-updated }}
  issues-updated:
    description: 'Number of issues with updated blocked status'
    value: ${{ steps.watcher.outputs.issues-updated }}
  dependencies-resolved:
    description: 'Number of dependency chains resolved'
    value: ${{ steps.watcher.outputs.dependencies-resolved }}

runs:
  using: 'composite'
  steps:
    - name: Generate Issues from PRDs
      id: generate
      if: inputs.action-mode == 'generate' || inputs.action-mode == 'full'
      uses: ./actions/taskmaster-generate
      with:
        complexity-threshold: ${{ inputs.complexity-threshold }}
        max-depth: ${{ inputs.max-depth }}
        prd-path-glob: ${{ inputs.prd-path-glob }}
        taskmaster-args: ${{ inputs.taskmaster-args }}
        github-token: ${{ inputs.github-token }}
    
    - name: Breakdown Issues
      id: breakdown
      if: inputs.action-mode == 'breakdown' || inputs.action-mode == 'full'
      uses: ./actions/taskmaster-breakdown
      with:
        breakdown-max-depth: ${{ inputs.breakdown-max-depth }}
        complexity-threshold: ${{ inputs.complexity-threshold }}
        taskmaster-args: ${{ inputs.taskmaster-args }}
        github-token: ${{ inputs.github-token }}
    
    - name: Watch Dependencies
      id: watcher
      if: inputs.action-mode == 'watcher' || inputs.action-mode == 'full'
      uses: ./actions/taskmaster-watcher
      with:
        scan-mode: ${{ inputs.scan-mode }}
        github-token: ${{ inputs.github-token }}

branding:
  icon: 'list'
  color: 'blue'