name: 'Taskmaster Breakdown'
description: 'Break down GitHub issues into manageable sub-tasks via slash commands. Triggered by issue comments starting with "/breakdown".'
author: 'cmbrose'

inputs:
  breakdown-max-depth:
    description: 'Maximum depth for breakdown recursion. Controls how many levels deep the task decomposition will go.'
    required: false
    default: '2'
  complexity-threshold:
    description: 'Complexity threshold for task breakdown. Tasks with complexity scores above this value will be further decomposed.'
    required: false
    default: '40'
  taskmaster-args:
    description: 'Additional command-line arguments to pass to the Taskmaster CLI tool for advanced configuration.'
    required: false
    default: ''
  github-token:
    description: 'GitHub personal access token with Issues write permissions for creating sub-issues and updating parent issues.'
    required: true

outputs:
  sub-issues-created:
    description: 'Number of sub-issues successfully created during the breakdown process (integer)'
  parent-issue-updated:
    description: 'Boolean indicator whether the parent issue was successfully updated with sub-issue links (true/false)'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
      shell: bash
      working-directory: ${{ github.action_path }}
    
    - name: Run Taskmaster Breakdown
      run: npx ts-node src/main.ts
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_BREAKDOWN-MAX-DEPTH: ${{ inputs.breakdown-max-depth }}
        INPUT_COMPLEXITY-THRESHOLD: ${{ inputs.complexity-threshold }}
        INPUT_TASKMASTER-ARGS: ${{ inputs.taskmaster-args }}
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}

branding:
  icon: 'git-branch'
  color: 'purple'