name: 'Taskmaster Breakdown'
description: 'Break down GitHub issues into manageable sub-tasks via slash commands. Triggered by issue comments starting with "/breakdown".'
author: 'cmbrose'

inputs:
  breakdown-max-depth:
    description: 'Maximum depth for breakdown recursion. Controls how many levels deep the task decomposition will go.'
    required: false
    default: '2'
  complexity-threshold:
    description: 'Complexity threshold for task breakdown. Tasks with complexity scores above this value will be further decomposed.'
    required: false
    default: '40'
  taskmaster-args:
    description: 'Additional command-line arguments to pass to the Taskmaster CLI tool for advanced configuration.'
    required: false
    default: ''
  github-token:
    description: 'GitHub personal access token with Issues write permissions for creating sub-issues and updating parent issues.'
    required: true

outputs:
  sub-issues-created:
    description: 'Number of sub-issues successfully created during the breakdown process (integer)'
  parent-issue-updated:
    description: 'Boolean indicator whether the parent issue was successfully updated with sub-issue links (true/false)'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'git-branch'
  color: 'purple'