name: 'Taskmaster Watcher'
description: 'Watch for issue changes and update dependencies/blocked status'
author: 'Taskmaster Team'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  scan-mode:
    description: 'Scan mode: webhook (single issue) or full (all issues)'
    required: false
    default: 'webhook'

outputs:
  issues-updated:
    description: 'Number of issues with updated blocked status'
  dependencies-resolved:
    description: 'Number of dependency chains resolved'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
      shell: bash
      working-directory: ${{ github.action_path }}
    
    - name: Run Taskmaster Watcher
      run: npx ts-node src/main.ts
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
        INPUT_SCAN-MODE: ${{ inputs.scan-mode }}

branding:
  icon: 'eye'
  color: 'green'