name: 'Taskmaster Generate'
description: 'Generate task graph and GitHub issues from PRD files'
author: 'Taskmaster Team'

inputs:
  complexity-threshold:
    description: 'Maximum complexity threshold for task breakdown'
    required: false
    default: '40'
  max-depth:
    description: 'Maximum depth for automatic task recursion'
    required: false
    default: '3'
  prd-path-glob:
    description: 'Path glob pattern for PRD files'
    required: false
    default: 'docs/**.prd.md'
  taskmaster-args:
    description: 'Additional arguments to pass to Taskmaster CLI'
    required: false
    default: ''
  taskmaster-version:
    description: 'Version of Taskmaster CLI to use'
    required: false
    default: '1.0.0'
  taskmaster-base-url:
    description: 'Base URL for Taskmaster CLI downloads'
    required: false
    default: 'https://github.com/taskmaster-ai/taskmaster/releases/download'
  force-download:
    description: 'Force re-download of Taskmaster CLI binary'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token for API access'
    required: true

outputs:
  task-graph:
    description: 'Path to generated task graph JSON file'
  task-graph-generated:
    description: 'Whether task-graph.json was successfully generated (true/false)'
  issues-created:
    description: 'Number of issues created or updated'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
      shell: bash
      working-directory: ${{ github.action_path }}
    
    - name: Run Taskmaster Generate
      run: npx ts-node src/main.ts
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_COMPLEXITY-THRESHOLD: ${{ inputs.complexity-threshold }}
        INPUT_MAX-DEPTH: ${{ inputs.max-depth }}
        INPUT_PRD-PATH-GLOB: ${{ inputs.prd-path-glob }}
        INPUT_TASKMASTER-ARGS: ${{ inputs.taskmaster-args }}
        INPUT_TASKMASTER-VERSION: ${{ inputs.taskmaster-version }}
        INPUT_TASKMASTER-BASE-URL: ${{ inputs.taskmaster-base-url }}
        INPUT_FORCE-DOWNLOAD: ${{ inputs.force-download }}
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}

branding:
  icon: 'list'
  color: 'blue'