name: Auto Publish and Merge PR on Assignment

on:
  pull_request:
    types: [assigned]

jobs:
  publish-and-merge:
    runs-on: ubuntu-latest
    if: contains(fromJson(toJson(github.event.pull_request.assignees)).*.login, 'cmbrose')
    steps:
      - name: Publish draft PR if needed and merge
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            // Publish if draft
            if (pr.data.draft) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                draft: false,
              });
              console.log('Published draft PR');
            } else {
              console.log('PR is already published');
            }

            // Merge the PR
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash', // or 'merge' or 'rebase'
            });
            console.log('Merged PR'); 