name: Reformat Issue Body

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue-number:
        description: 'Issue number to re-format'
        required: true
        type: string

jobs:
  format-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      models: read

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install tools
        run: |
          pip install --quiet llm
          llm install llm-github-models
          sudo apt-get update -qq
          sudo apt-get install -yqq jq

      - name: Resolve issue number
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "issues" ]; then
            echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
          else
            echo "ISSUE_NUMBER=${{ inputs.issue-number }}" >> $GITHUB_ENV
          fi

      - name: Re-format body with LLM
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_MODELS_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BODY=$(gh api repos/${{ github.repository }}/issues/${ISSUE_NUMBER} --jq .body)
          NEW_BODY=$(printf '%s' "$BODY" | llm -m github/gpt-4o --system "Improve the formatting of this GitHub issue body. Preserve all content but clean up markdown, headings, code blocks, and lists for readability.")
          gh api --method PATCH repos/${{ github.repository }}/issues/${ISSUE_NUMBER} -f body="$NEW_BODY"
